config:
  enabled:
    type: checkbox
    label: Activated ?
    help: Do you want to activate Stripe Payment
  stripe_element:
    type: checkbox
    label: Activated stripe element else paiement with checkout ?
    help: Do you want to activate Stripe element
  secret_key:
    type: text
    required: true
    label: Your secret key
    help: You can see all your keys in your <a target="_blank" href="https://dashboard.stripe.com/">Stripe dashboard</a>. Also note that you can place your test or your live API keys
  publishable_key:
    type: text
    required: true
    label: Your publishable key (test or live)
  webhooks_key:
    type: text
    required: true
    label: Your webhooks secret key (test or live)
  secure_url:
    type: text
    required: true
    label: Your chose a key for secure webhook return